<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ipchange_detector</RootNamespace>
    <Nullable>enable</Nullable>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ipmonitor-interface\ipmonitor-interface.csproj" />
    <ProjectReference Include="..\ipmonitor-model\ipmonitor-model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutofacSerilogIntegration" Version="5.0.0" />
    <PackageReference Include="AutoFixture.AutoMoq" Version="4.18.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.6" />
    <PackageReference Include="microsoft.extensions.http" Version="10.0.6" />
    <PackageReference Include="system.io.abstractions" Version="22.1.1" />
  </ItemGroup>

</Project>
